### ISSUE TITLE
do you have the code of extracting features from sentence or image?

### ISSUE THREAD

**Issue by xogo123** [lwwang/Two_branch_network#1]
Hi, I like your work and try to use it.
But how can I get the embedding if I input sentence or image?
I can only find the code about the model which could transfer sentence or image feature to final embedding. But I cannot find the code to extract feature from raw sentence or image.
Thanks.

**Comment by lwwang** [comment]
Thanks for your interests. 
For image feature representation, we use pre-trained VGG 19 network, which is pretrained on imagenet. 
For sentence feature representation, we use the method from : 
Klein, Benjamin, et al. "Fisher vectors derived from hybrid gaussian-laplacian mixture models for image annotation. CVPR 2015".

**Comment by lwwang** [comment]
As I replied, For sentence feature representation, we use the method from :
Klein, Benjamin, et al. "Fisher vectors derived from hybrid gaussian-laplacian mixture models for image annotation. CVPR 2015".

They provide the code here:
https://owncloud.cs.tau.ac.il/index.php/s/vb7ys8Xe8J8s8vo

For image features, it is VGG19 features and you can use matcaffe or many other standard tools to extract.
