### ISSUE TITLE
Sample features for training

### ISSUE THREAD

**Issue by sxs4337** [lwwang/Two_branch_network#2]
Thanks for this great work! The code is very well written and easy to follow.
Would it please be possible to share some sample feature files for training the network. It would help in understanding the input data format and preparing data files for other datasets.

During training, do the image features have to be as single .mat file (would it not be a very large file)?
Also, is there any specific reason to have .mat files for image features and .h5 files for sentence features?

Thanks again.

**Comment by lwwang** [comment]
.h5 files can sometimes make it faster during training. 
For sentence feature extraction, we use the work from the following, 
"Klein, Benjamin, et al. "Fisher vectors derived from hybrid gaussian-laplacian mixture models for image annotation." CVPR 2015"
